### ISSUE TITLE
improve the logos in `build/`

### ISSUE THREAD

**Issue by calum** [calum/alexa-drag-race-skill#6]
![29c2a3a6-2393-4f5e-bbb7-a95bbeeac63c](https://user-images.githubusercontent.com/22115035/32139430-54f2d9da-bc40-11e7-9630-dc2c31012c32.png)

**Comment by daniels-sc** [comment]
I've made a PR to fix this issue.

**Comment by calum** [comment]
Closed by sc-daniels PR
